TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devsamsm300.db
DATA += devsamsm300.proto

#=======================================
include $(TOP)/configure/RULES
